Repository ojo-network/price-feeder, pull requests merged in 2023-04, with the labels that each got.

#87 chore: update osmosis API endpoint
  oracle/provider/osmosisv2.go
  price-feeder.example.toml
Labels: S:backport/umee

#107 feat: log error instead of failing on failed USD conversion
  oracle/convert.go
  oracle/convert_test.go
  oracle/oracle.go
  oracle/oracle_test.go
Labels: S:backport/umee

#112 fix: Update outdated and vulnerable dependencies in umee branch
  go.mod
  go.sum
Labels: A:Automerge

#89 fix: html template package
  router/v1/router.go
Labels: A:Automerge, S:backport/umee

#116 chore: remove old fin provider
  config/supported_assets.go
  oracle/oracle.go
  oracle/provider/fin.go
  oracle/provider/fin_test.go
  oracle/provider/provider.go
Labels: A:Automerge, S:backport/umee
